feature/todo-api
Poszkolni/poszkolni_backend pull request #5
Opened 2021-03-28 18:33 UTC by nadrowskyy

https://trello.com/c/rKsDIunL/4-basic-api-for-todo-list

2021-03-28 18:47 UTC, nadrowskyy commented
WP: feature/todo-api

2021-03-29 22:11 UTC, KubaC701 requested changes

2021-03-29 22:11 UTC, KubaC701 commented on apps/api/views.py
> +@api_view(['POST'])
Change this method to PUT

2021-03-29 22:14 UTC, KubaC701 approved these changes

2021-03-29 22:14 UTC, merged